name: Build and Deploy

on:
    push:
        branches:
            - main
            - master

jobs:
    deploy:
        name: Deploy to 404-MOON
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: unnecessary
                      
            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
            - name: Upload code to VM
              run: rsync -avz ./ root@${{ secrets.SSH_HOST }}:/root/access

            - name: SSH into VM and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /root/access
                      screen -X -S rootaccess kill
                      npm ci
                      npm run build
                      screen -S rootaccess -d -m npm start
